[package]
name = "locutra"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.114"
wasm-bindgen = "0.2.92"
js-sys = "0.3.69"
brotli-decompressor = "2.5.1" 
lazy_static = "1.4.0"